"""Add owner_id column to debates table

Revision ID: 08f4df733b03
Revises: 7a74adf27b04
Create Date: 2023-07-19 09:56:37.709447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f4df733b03'
down_revision = '7a74adf27b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debates', schema=None) as batch_op:

        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))

        batch_op.create_foreign_key('fk_debates_owner_id_users', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_debates_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
